version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
#  pre_build:
#    commands:
#      - pip install --upgrade pip
#      - pip install poetry==1.1.4
#      - poetry env use 3.9
#      - poetry shell
#      - poetry install
#  build:
#    commands:
#      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'ec2/**/*'
    - 'potosi/**/*.py'
    - poetry.lock
    - pyproject.toml
    - appspec.yml
