AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DBInstanceIdentifier:
    Type: String
    Default: "potosi"
  DBEngine:
    Type: String
    Default: "postgres"
  DBEngineVersion:
    Type: String
    Default: "12.4"
  DBSourceRegion:
    Type: String
    Default: "us-east-1"
  DBInstanceClass:
    Type: String
    Default: "db.t2.micro"
  DBStorageType:
    Type: String
    Default: "gp2"
  DBAllocatedStorage:
    Type: Number
    Default: 20
  DBName:
    Type: String
    Default: "{{resolve:ssm:/potosi/db_name:1}}"
  DBUser:
    Type: String
    Default: "{{resolve:ssm:/potosi/db_username:1}}"
  DBPassword:
    Type: String
    Default: "{{resolve:ssm-secure:/potosi/db_password:1}}"
    NoEcho: True
  MainStackName:
    Type: String
Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier:
        Ref: DBInstanceIdentifier
      DBName:
        Ref: DBName
      AllocatedStorage:
        Ref: DBAllocatedStorage
      DBInstanceClass:
        Ref: DBInstanceClass
      StorageType:
        Ref: DBStorageType
      Engine:
        Ref: DBEngine
      EngineVersion:
        Ref: DBEngineVersion
      MasterUsername:
        Ref: DBUser
      MasterUserPassword:
        Ref: DBPassword
      PubliclyAccessible: True
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
      VPCSecurityGroups:
        - !GetAtt DBEC2SecurityGroup.GroupId
  #      VPCSecurityGroups:
  #        - !GetAtt VPC.DefaultSecurityGroup
  #      DBSubnetGroupName:
  #        Ref: DBSubnetGroup

  #  DBSecurityGroup:
  #    Type: AWS::RDS::DBSecurityGroup
  #    Properties:
  #      DBSecurityGroupIngress:
  #        EC2SecurityGroupName:
  #          Ref: SecurityGroup
  #      GroupDescription: Potosi Backend Access
  #      Tags:
  #        - Key: Name
  #          Value: !Ref AWS::StackName

  DBEC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open database for access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '5432'
          ToPort: '5432'
          SourceSecurityGroupName:
#            Ref: SecurityGroup
            Fn::ImportValue:
              !Sub "${MainStackName}-SecurityGroupID"
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
Outputs:
  DBEndpoint:
    Description: "Endpoint of the newly created RDS PostgreSQL master"
    Value: !GetAtt DBInstance.Endpoint.Address
  PortDB:
    Description: "Port of the newly created RDS PostgreSQL master and replica"
    Value: !GetAtt DBInstance.Endpoint.Port
  JdbcConnString:
    Description: "JDBC connection string of newly created RDS PostgreSQL master, w/o password"
    Value: !Join
      - ""
      - - "jdbc:postgresql://"
        - !GetAtt DBInstance.Endpoint.Address
        - ":"
        - !GetAtt DBInstance.Endpoint.Port
        - "/"
        - "{{resolve:ssm:/potosi/db_name:1}}"
        - "?user="
        - "{{resolve:ssm:/potosi/db_username:1}}"
        - "&password="
        - ""
